Document: countdowntimer
Title: Debian countdowntimer Manual
Author: <insert document author here>
Abstract: This manual describes what countdowntimer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/countdowntimer/countdowntimer.sgml.gz

Format: postscript
Files: /usr/share/doc/countdowntimer/countdowntimer.ps.gz

Format: text
Files: /usr/share/doc/countdowntimer/countdowntimer.text.gz

Format: HTML
Index: /usr/share/doc/countdowntimer/html/index.html
Files: /usr/share/doc/countdowntimer/html/*.html


